server:
  port: 8082
flowable:
  async-executor-activate: false
#  database-schema-update: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable_2021_07_12?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: qazOKM123
    driver-class-name: com.mysql.jdbc.Driver

